// server.js
require('dotenv').config();
const express = require('express');
const session = require('express-session');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const http = require('http');
const path = require('path');
const { Server } = require('socket.io');

const app = express();
const server = http.createServer(app);
const io = new Server(server);

// config
const PORT = process.env.PORT || 3000;
const SESSION_SECRET = process.env.SESSION_SECRET || 'please_change_this';
const SHARED_PASSWORD = process.env.SHARED_PASSWORD || 'BeastBee';
const ROOM_NAME = process.env.ROOM_NAME || 'room123';

// middleware
app.use(express.static(path.join(__dirname, 'public')));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(cookieParser());
app.set('trust proxy', 1);

app.use(session({
  secret: SESSION_SECRET,
  resave: false,
  saveUninitialized: false,
  cookie: { maxAge: 24*60*60*1000 }
}));

// login: shared password + display username
app.post('/login', (req, res) => {
  const { username, password, room } = req.body;
  if (!username || !password) return res.status(400).json({ ok:false, message: 'username and password required' });

  if (password !== SHARED_PASSWORD) return res.status(401).json({ ok:false, message: 'Invalid shared password' });

  const usedRoom = room && room.trim() ? room.trim() : ROOM_NAME;
  req.session.user = { username: username.trim().slice(0,32), room: usedRoom };
  return res.json({ ok: true });
});

app.post('/logout', (req, res) => {
  req.session.destroy(_ => {
    res.json({ ok: true });
  });
});

app.get('/session', (req, res) => {
  if (req.session && req.session.user) return res.json({ ok:true, user: req.session.user });
  return res.json({ ok:false });
});

app.get('/chat', (req, res) => {
  if (!req.session || !req.session.user) return res.redirect('/login.html');
  return res.sendFile(path.join(__dirname, 'public', 'chat.html'));
});

// Socket.io logic
// We will forward typing events and seen receipts to the other participant in the room.
// Room size limited to 2.
io.on('connection', (socket) => {
  socket.on('joinRoom', async ({ room, username }) => {
    if (!room || !username) {
      socket.emit('errorMsg', 'Missing room or username');
      return;
    }

    const clients = await io.in(room).allSockets();
    if (clients.size >= 2) {
      socket.emit('roomFull');
      return;
    }

    socket.join(room);
    socket.data = { room, username };

    // notify others
    socket.to(room).emit('userJoined', { username });

    // tell this user the participant list
    const participants = [];
    for (const id of clients) {
      const s = io.sockets.sockets.get(id);
      if (s && s.data && s.data.username) participants.push(s.data.username);
    }
    participants.push(username);
    socket.emit('joined', { participants });
    io.in(room).emit('participants', { count: (await io.in(room).allSockets()).size });
  });

  // forward message to room (message contains id generated by sender)
  socket.on('message', ({ room, username, text, id }) => {
    if (!room || !text || !id) return;
    // broadcast to room
    io.in(room).emit('message', { username, text, id, ts: Date.now() });
    // Note: since we don't persist, "delivered" is assumed because server forwarded to room sockets.
  });

  // typing indicator from a client -> broadcast to others in same room
  socket.on('typing', ({ room, username }) => {
    if (!room) return;
    socket.to(room).emit('typing', { username });
  });
  socket.on('stopTyping', ({ room, username }) => {
    if (!room) return;
    socket.to(room).emit('stopTyping', { username });
  });

  // read receipt: recipient tells server which message id was seen; server relays to room
  socket.on('messageSeen', ({ room, messageId, seenBy }) => {
    if (!room || !messageId) return;
    // broadcast to room (sender will update UI if they are in room)
    io.in(room).emit('messageSeen', { messageId, seenBy, ts: Date.now() });
  });

  socket.on('disconnecting', () => {
    const { room, username } = socket.data || {};
    if (room && username) {
      socket.to(room).emit('userLeft', { username });
    }
  });
});

server.listen(PORT, () => {
  console.log(`Server listening on port ${PORT}`);
});
